version: "3.9"

services:
   
    db:
       image: postgres:15
       container_name: postgres_db
       restart: always
       environment:
          
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: notesdb
       ports:
        -  "5432:5432"

       volumes:
         - postgres_data:/var/lib/postgresql/data 

    backend:
        build:  ./backend
        container_name:  flask_backend
        restart: always
        ports:
           - "5000:5000"
        depends_on:
           - db          
           

    frontend:
         build: ./frontend
         container_name: react_frontend
         restart: always
         ports:
           - "5173:5173"

         depends_on:
           - backend         

volumes:
   postgres_data: 
